name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # GitHub will auto-resolve to 3.12.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify Python version
        run: python --version